name: Build and push Docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          hostnamectl

  build-and-push2:
    runs-on: ubuntu-latest
    needs: build-and-push1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build2
        run: |
          hostnamectl

  build-and-push3:
    runs-on: ubuntu-latest
    needs: build-and-push2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build3
        run: |
          hostnamectl
